// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBH_API.Data;

#nullable disable

namespace QLBH_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLBH_API.Models.tbDanhMuc", b =>
                {
                    b.Property<int>("MADANHMUC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MADANHMUC"));

                    b.Property<int?>("DANHMUCCHA")
                        .HasColumnType("int");

                    b.Property<string>("MOTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENDANHMUC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MADANHMUC");

                    b.ToTable("tbDANHMUC");
                });

            modelBuilder.Entity("QLBH_API.Models.tbGioHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("MAKHACHHANG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MASANPHAM")
                        .HasColumnType("int");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("tbGIOHANG");
                });

            modelBuilder.Entity("QLBH_API.Models.tbSanPham", b =>
                {
                    b.Property<int>("MASANPHAM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MASANPHAM"));

                    b.Property<decimal?>("DONGIA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HINHANH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MADANHMUC")
                        .HasColumnType("int");

                    b.Property<string>("MOTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SOLUONG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TENSANPHAM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MASANPHAM");

                    b.ToTable("tbSANPHAM");
                });
#pragma warning restore 612, 618
        }
    }
}
